# Generated by Django 6.0 on 2026-02-15 21:42

import django.db.models.deletion
import stock.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='StockItem',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('product_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Ürün Kodu')),
                        ('product_name', models.CharField(db_index=True, max_length=255, verbose_name='Ürün Adı')),
                        ('quality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kalite')),
                        ('waybill_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='İrsaliye No')),
                        ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                        ('stock_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stok Alanı')),
                        ('unit', models.CharField(default='Adet', max_length=50, verbose_name='Birim')),
                        ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Miktar (Kalan)')),
                        ('initial_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giriş Miktarı')),
                        ('min_stock_level', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Kritik Stok Miktarı')),
                        ('document', models.FileField(blank=True, null=True, upload_to=stock.models.stock_directory_path, verbose_name='Dosya (PDF/Resim)')),
                        ('category', models.CharField(choices=[('HAM MADDE', 'Ham Madde'), ('YARI MAMUL', 'Yarı Mamul'), ('MAMUL', 'Mamul'), ('SARF MALZEME', 'Sarf Malzeme'), ('HIRDAVAT', 'Hırdavat')], default='HAM MADDE', max_length=50, verbose_name='Kategori')),
                        ('sub_category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alt Kategori')),
                        ('unit_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Birim Ağırlık (kg)')),
                        ('shelf_basket', models.CharField(blank=True, max_length=50, null=True, verbose_name='Raf/Sepet No')),
                        ('supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tedarikçi')),
                        ('lot_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lot No')),
                        ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/', verbose_name='QR Kod')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                    ],
                    options={
                        'verbose_name': 'Stok Kalemi',
                        'verbose_name_plural': 'Stok Listesi',
                        'db_table': 'products_stockitem',
                    },
                ),
                migrations.CreateModel(
                    name='StockMovement',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar')),
                        ('movement_type', models.CharField(choices=[('IN', 'Giriş'), ('OUT', 'Çıkış')], default='OUT', max_length=10, verbose_name='Hareket Tipi')),
                        ('project', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kullanılacak Proje')),
                        ('receiver', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teslim Alan')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Tarihi')),
                        ('performer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                        ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.stockitem', verbose_name='Stok Kalemi')),
                    ],
                    options={
                        'verbose_name': 'Stok Hareketi',
                        'verbose_name_plural': 'Stok Hareketleri',
                        'db_table': 'products_stockmovement',
                    },
                ),
            ],
            database_operations=[],
        )
    ]
