# Generated by Django 6.0 on 2026-02-27 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Firma Adı')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='İletişim Kişisi')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon Numarası')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tedarikçi',
                'verbose_name_plural': 'Tedarikçiler',
            },
        ),
        migrations.CreateModel(
            name='PurchaseProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Süreç Başlığı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Teklif Alındı', 'Teklif Alındı'), ('Onaylandı', 'Onaylandı'), ('Sipariş Verildi', 'Sipariş Verildi'), ('Teslim Alındı', 'Teslim Alındı'), ('İptal Edildi', 'İptal Edildi')], default='Bekliyor', max_length=50, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Satın Alma Süreci',
                'verbose_name_plural': 'Satın Alma Süreçleri',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Ürün/Hizmet Adı')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miktar')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('Talep Edildi', 'Talep Edildi'), ('Süreçte', 'Süreçte'), ('Tamamlandı', 'Tamamlandı'), ('İptal', 'İptal')], default='Talep Edildi', max_length=50, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='purchases.purchaseprocess', verbose_name='İlgili Süreç')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.supplier', verbose_name='Önerilen Tedarikçi')),
            ],
            options={
                'verbose_name': 'Satın Alma Talebi',
                'verbose_name_plural': 'Satın Alma Talepleri',
            },
        ),
    ]
