# Generated by Django 6.0 on 2026-02-13 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesoffer',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.customer', verbose_name='Müşteri'),
        ),
    ]
