# Generated by Django 6.0 on 2026-02-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_salesoffer_customer_name_salesoffer_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoffer',
            name='currency',
            field=models.CharField(choices=[('TL', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'Sterlin (£)')], default='TL', max_length=3, verbose_name='Para Birimi'),
        ),
    ]
