# Generated by Django 6.0 on 2026-02-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesoffer_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoffer',
            name='language',
            field=models.CharField(choices=[('TR', 'Türkçe'), ('EN', 'İngilizce')], default='TR', max_length=2, verbose_name='Dil'),
        ),
    ]
