# Generated by Django 6.0 on 2026-02-13 22:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesoffer_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoffer',
            name='advance_payment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Avans'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=255, verbose_name='Şube'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=50, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Banka Adı'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='bank_recipient',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alıcı Adı'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='bank_swift',
            field=models.CharField(blank=True, max_length=50, verbose_name='SWIFT No'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='company_address',
            field=models.TextField(blank=True, verbose_name='Firma Adresi'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='company_name',
            field=models.CharField(blank=True, default='KORUCU MAKİNA', max_length=255, verbose_name='Firma Adı'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='company_tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Vergi No'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='company_tax_office',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vergi Dairesi'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Teslim Tarihi'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='delivery_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Teslim Yeri'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='offer_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Teklif Tarihi'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='offer_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teklif No'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ödeme Metodu'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='revision_number',
            field=models.IntegerField(default=0, verbose_name='Revizyon No'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='terms',
            field=models.TextField(blank=True, verbose_name='Anlaşma Şartları'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='validity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Geçerlilik Tarihi'),
        ),
    ]
