# Generated by Django 6.0 on 2026-02-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salesoffer_advance_payment_salesoffer_bank_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesoffer',
            name='offer_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Teklif No'),
        ),
    ]
