# Generated by Django 6.0 on 2026-02-15 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_stockmovement_stock_item_and_more'),
        ('sales', '0007_alter_salesoffer_offer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesofferitem',
            name='subpart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.subpart', verbose_name='Alt Parça'),
        ),
        migrations.AlterField(
            model_name='salesofferitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Ürün'),
        ),
        migrations.AlterField(
            model_name='salesofferitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ürün/Parça Adı'),
        ),
    ]
