# Generated by Django 6.0 on 2026-02-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_salesofferitem_subpart_alter_salesofferitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoffer',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='teklifler/', verbose_name='Teklif PDF'),
        ),
    ]
