# Generated by Django 6.0 on 2026-02-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_salesoffer_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoffer',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Müşteriye Gönderildi'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme Tarihi'),
        ),
    ]
