# Generated by Django 6.0 on 2026-02-22 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesoffer_is_sent_salesoffer_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_note', models.TextField(verbose_name='Durum Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='sales.salesoffer', verbose_name='Teklif')),
            ],
            options={
                'verbose_name': 'Teklif İlerleme Durumu',
                'verbose_name_plural': 'Teklif İlerleme Durumları',
                'ordering': ['-created_at'],
            },
        ),
    ]
