# Generated by Django 6.0 on 2026-02-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_offerprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoffer',
            name='alarm_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Alarm Tarihi'),
        ),
    ]
