# Generated by Django 6.0 on 2026-02-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_salesoffer_alarm_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoffer',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Proje Adı'),
        ),
    ]
