# Generated by Django 6.0 on 2025-12-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=50, verbose_name='Malzeme Kodu')),
                ('material_name', models.CharField(max_length=255, verbose_name='Malzeme Adı')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ağırlığı')),
                ('standard', models.CharField(max_length=100, verbose_name='Standardı')),
                ('country', models.CharField(max_length=100, verbose_name='Ülke')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
    ]
