# Generated by Django 6.0 on 2025-12-26 21:06

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=products.models.product_directory_path, verbose_name='PDF Dosyası'),
        ),
    ]
