# Generated by Django 6.0 on 2025-12-26 21:18

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='product',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=products.models.product_directory_path, verbose_name='Dosya (PDF/Resim)'),
        ),
    ]
