# Generated by Django 6.0 on 2025-12-26 21:47

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_pdf_file_product_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=50, verbose_name='Malzeme Kodu')),
                ('material_name', models.CharField(max_length=255, verbose_name='Malzeme Adı')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ağırlığı')),
                ('quality', models.CharField(max_length=100, verbose_name='Kalite')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('quality_doc', models.FileField(blank=True, null=True, upload_to=products.models.subpart_directory_path, verbose_name='Kalite Belgesi')),
                ('visual_doc', models.FileField(blank=True, null=True, upload_to=products.models.subpart_directory_path, verbose_name='Görsel Dosya')),
            ],
            options={
                'verbose_name': 'Alt Parça',
                'verbose_name_plural': 'Alt Parçalar',
            },
        ),
    ]
