# Generated by Django 6.0 on 2026-01-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_subpart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpart',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Ağırlığı'),
        ),
    ]
