# Generated by Django 6.0 on 2026-01-07 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_subpart_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subparts', to='products.product')),
                ('subpart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subpart')),
            ],
        ),
    ]
