# Generated by Django 6.0 on 2026-01-30 12:28

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productsubpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='Ürün Kodu')),
                ('product_name', models.CharField(max_length=255, verbose_name='Ürün Adı')),
                ('quality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kalite')),
                ('waybill_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='İrsaliye No')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('stock_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stok Alanı')),
                ('unit', models.CharField(default='Adet', max_length=50, verbose_name='Birim')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Miktar')),
                ('document', models.FileField(blank=True, null=True, upload_to=products.models.stock_directory_path, verbose_name='Dosya (PDF/Resim)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stok Kalemi',
                'verbose_name_plural': 'Stok Listesi',
            },
        ),
    ]
