# Generated by Django 6.0 on 2026-02-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_stockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='category',
            field=models.CharField(choices=[('HAM MADDE', 'Ham Madde'), ('YARI MAMUL', 'Yarı Mamul'), ('MAMUL', 'Mamul'), ('SARF MALZEME', 'Sarf Malzeme')], default='HAM MADDE', max_length=50, verbose_name='Kategori'),
        ),
    ]
