# Generated by Django 6.0 on 2026-02-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_stockitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='category',
            field=models.CharField(choices=[('HAM MADDE', 'Ham Madde'), ('YARI MAMUL', 'Yarı Mamul'), ('MAMUL', 'Mamul'), ('SARF MALZEME', 'Sarf Malzeme'), ('HIRDAVAT', 'Hırdavat')], default='HAM MADDE', max_length=50, verbose_name='Kategori'),
        ),
    ]
