# Generated by Django 6.0 on 2026-02-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_stockitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='sub_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alt Kategori'),
        ),
    ]
