# Generated by Django 6.0 on 2026-02-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_stockitem_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='lot_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lot No'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/', verbose_name='QR Kod'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='shelf_basket',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Raf/Sepet No'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tedarikçi'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='unit_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Birim Ağırlık (kg)'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Ürün Kodu'),
        ),
    ]
