# Generated by Django 6.0 on 2026-02-09 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_stockitem_lot_no_stockitem_qr_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPartMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('Adet', 'Adet'), ('Metre', 'Metre'), ('Metrekare', 'Metrekare'), ('Kg', 'Kg')], default='Adet', max_length=50, verbose_name='Birim')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Miktar')),
                ('fireli_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Fireli Ağırlık')),
                ('net_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Net Ağırlık')),
                ('galvanized_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Galvanizli Ağırlık')),
                ('total_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Toplam Ağırlık')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Birim Fiyat')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.stockitem', verbose_name='Stok Malzemesi')),
                ('subpart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='products.subpart')),
            ],
        ),
    ]
