# Generated by Django 6.0 on 2026-02-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_subpartmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpartmaterial',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='Miktar'),
        ),
    ]
