# Generated by Django 6.0 on 2026-02-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='initial_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giriş Miktarı'),
        ),
    ]
