# Generated by Django 6.0 on 2026-02-11 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_stockitem_initial_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='initial_quantity',
        ),
    ]
