# Generated by Django 6.0 on 2026-02-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_stockitem_initial_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='initial_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giriş Miktarı'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Miktar (Kalan)'),
        ),
    ]
