# Generated by Django 6.0 on 2026-02-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_stockitem_initial_quantity_alter_stockitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Kritik Stok Miktarı'),
        ),
    ]
