# Generated by Django 6.0 on 2026-02-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_stockitem_min_stock_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Malzeme Adı'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='product_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='subpart',
            name='material_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Malzeme Adı'),
        ),
    ]
