# Generated by Django 6.0 on 2026-02-15 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_material_name_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='stockmovement',
                    name='stock_item',
                ),
                migrations.AlterField(
                    model_name='subpartmaterial',
                    name='stock_item',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockitem', verbose_name='Stok Malzemesi'),
                ),
                migrations.RemoveField(
                    model_name='stockmovement',
                    name='performer',
                ),
                migrations.DeleteModel(
                    name='StockItem',
                ),
                migrations.DeleteModel(
                    name='StockMovement',
                ),
            ],
            database_operations=[],
        )
    ]
